from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.common.models import BaseModel

# ── Alert rule types ──────────────────────────────────────────────────────────
ALERT_TYPES = [
    "margin_below",      # avg margin < threshold % in last N days
    "sync_failed",       # store sync job ended in error
    "fulfillment_error", # auto-fulfill job raised an exception
    "stock_below",       # any product variant inventory < threshold units
]


class AlertRule(BaseModel):
    """A user-defined trigger that generates Notifications when it fires."""
    __tablename__ = "alert_rules"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Which store to watch — null means "all stores"
    store_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("stores.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    alert_type: Mapped[str] = mapped_column(String(40), nullable=False)
    # For margin_below: threshold as a percentage 0–100
    threshold: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Rolling window in days used by margin_below evaluation
    window_days: Mapped[int] = mapped_column(default=7, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    notifications: Mapped[list["Notification"]] = relationship(
        "Notification", back_populates="rule", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<AlertRule type={self.alert_type!r} tenant={self.tenant_id}>"


class Notification(BaseModel):
    """An in-app notification generated by an AlertRule or the system."""
    __tablename__ = "notifications"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    rule_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("alert_rules.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    notification_type: Mapped[str] = mapped_column(String(40), nullable=False)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    is_read: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)

    rule: Mapped[AlertRule | None] = relationship("AlertRule", back_populates="notifications")

    def __repr__(self) -> str:
        return f"<Notification type={self.notification_type!r} read={self.is_read}>"
